"""
This type stub file was generated by pyright.
"""

import json
from __future__ import absolute_import
from ._file_cache import _FileCache
from .error import TwitterError
from .parse_tweet import ParseTweet
from .models import Category, DirectMessage, Hashtag, List, Media, Status, Trend, Url, User, UserStatus
from .api import Api

"""A library that provides a Python interface to the Twitter API."""
__author__ = 'The Python-Twitter Developers'
__email__ = 'python-twitter@googlegroups.com'
__copyright__ = 'Copyright (c) 2007-2016 The Python-Twitter Developers'
__license__ = 'Apache License 2.0'
__version__ = '3.5'
__url__ = 'https://github.com/bear/python-twitter'
__download_url__ = 'https://pypi.python.org/pypi/python-twitter'
__description__ = 'A Python wrapper around the Twitter API'
