"""
This type stub file was generated by pyright.
"""

class _FileCacheError(Exception):
    """Base exception class for FileCache related errors"""
    ...


class _FileCache(object):
    DEPTH = ...
    def __init__(self, root_directory=...) -> None:
        ...
    
    def Get(self, key):
        ...
    
    def Set(self, key, data):
        ...
    
    def Remove(self, key):
        ...
    
    def GetCachedTime(self, key):
        ...
    


