"""
This type stub file was generated by pyright.
"""

from twitter import Api

class Api(Api):
    def DebugEndpoint(self, verb=..., endpoint=..., data=...):
        """ Request a url and return raw data. For testing purposes only.

        Args:
            url:
                The web location we want to retrieve.
            verb:
                Either POST or GET.
            data:
                A dict of (str, unicode) key/value pairs.

        Returns:
            data
        """
        ...
    


