"""
This type stub file was generated by pyright.
"""

class Emoticons:
    POSITIVE = ...
    NEGATIVE = ...


class ParseTweet(object):
    regexp = ...
    regexp = ...
    def __init__(self, timeline_owner, tweet) -> None:
        """ timeline_owner : twitter handle of user account. tweet - 140 chars from feed; object does all computation on construction
            properties:
            RT, MT - boolean
            URLs - list of URL
            Hashtags - list of tags
        """
        ...
    
    def __str__(self) -> str:
        """ for display method """
        ...
    
    @staticmethod
    def getAttributeEmoticon(tweet):
        """ see if tweet is contains any emoticons, +ve, -ve or neutral """
        ...
    
    @staticmethod
    def getAttributeRT(tweet):
        """ see if tweet is a RT """
        ...
    
    @staticmethod
    def getAttributeMT(tweet):
        """ see if tweet is a MT """
        ...
    
    @staticmethod
    def getUserHandles(tweet):
        """ given a tweet we try and extract all user handles in order of occurrence"""
        ...
    
    @staticmethod
    def getHashtags(tweet):
        """ return all hashtags"""
        ...
    
    @staticmethod
    def getURLs(tweet):
        r""" URL : [http://]?[\w\.?/]+"""
        ...
    


